coverage:
  paths:
    - coverage/lcov.info
  acceptable: 70%
  exclude:
    - "tests/**/*"
    - "**/*.test.js"
    - "node_modules/**/*"

codeToTestRatio:
  code:
    - "src/**/*.js"
    - "src/**/*.jsx"
  test:
    - "tests/**/*.js"
    - "tests/**/*.test.js"
    - "tests/**/*.spec.js"
  acceptable: "1:0.5"

diff:
  paths:
    - coverage/lcov.info
  acceptable: 5%

comment:
  if: is_pull_request
  hideFooterLink: true
  message: |
    ## Code Coverage Report

    **Overall Coverage**: {{ .Coverage.Percent }}%
    {{- if .Coverage.Total }}
    **Lines Covered**: {{ .Coverage.Covered }}/{{ .Coverage.Total }}
    {{- end }}

    {{- if .Diff }}
    **Diff Coverage**: {{ .Diff.Percent }}%
    {{- if .Diff.Total }}
    **Diff Lines Covered**: {{ .Diff.Covered }}/{{ .Diff.Total }}
    {{- end }}
    {{- end }}

    {{- if .Coverage.Files }}
    ### Coverage by File
    {{- range .Coverage.Files }}
    {{- if lt .Percent 80.0 }}
    - ⚠️ `{{ .File }}`: {{ .Percent }}%
    {{- else }}
    - ✅ `{{ .File }}`: {{ .Percent }}%
    {{- end }}
    {{- end }}
    {{- end }}

    {{- if .Diff.Files }}
    ### Changed Files Coverage
    {{- range .Diff.Files }}
    - `{{ .File }}`: {{ .Percent }}%
    {{- end }}
    {{- end }}

push:
  if: true
  datastores:
    - github://ikevin127/expensify-app-mock/coverage
