coverage:
  paths:
    - coverage/lcov.info
  acceptable: 50%
  if: true

diff:
  acceptable: 5%

comment:
  if: is_pull_request
  hideFooterLink: true
  message: |
    ## 🏆 CUSTOM Code Coverage Report

    **Coverage:** {{ .Coverage.Percentage }}%
    **Total Lines:** {{ .Coverage.Total }}
    **Covered Lines:** {{ .Coverage.Covered }}
    **Code to Test Ratio:** {{ .CodeToTestRatio.Ratio }}

report:
  if: true
  datastores:
    - artifact://${GITHUB_REPOSITORY}
