coverage:
  paths:
    - coverage/lcov.info
  acceptable: 50%
  if: true

codeToTestRatio:
  code:
    - "src/**/*.js"
    - "src/**/*.jsx"
  test:
    - "tests/**/*.js"
    - "tests/**/*.test.js"
    - "tests/**/*.spec.js"
  acceptable: "1:1.2"
  if: true

diff:
  acceptable: 5%

comment:
  if: is_pull_request
  hideFooter: true
  template: |
    ## 📊 Code Coverage Report

    | Metric | Value |
    |-----------|-------|
    | **Coverage** | {{ .Coverage.Percentage }}% |
    | **Code Lines** | {{ .Coverage.Total }} |
    | **Covered Lines** | {{ .Coverage.Covered }} |
    {{- if .CodeToTestRatio }}
    | **Code to Test Ratio** | {{ .CodeToTestRatio.Ratio }} |
    {{- end }}

    {{- if .Coverage.Diff }}
    ### 📈 Coverage Changes
    {{ .Coverage.Diff }}
    {{- end }}

report:
  if: always
  datastores:
    - artifact://coverage-report
