coverage:
  paths:
    - coverage/lcov.info
    - coverage/coverage-summary.json
  acceptable: 70%
  exclude:
    - "tests/**/*"
    - "**/*.test.js"
    - "node_modules/**/*"

codeToTestRatio:
  code:
    - "src/**/*.{js,jsx,ts,tsx}"
  test:
    - "tests/**/*.{js,ts,test.js,test.ts,spec.js,spec.ts}"
  acceptable: "1:0.3"

comment:
  if: is_pull_request
  deletePrevious: true

diff:
  paths:
    - coverage/lcov.info
    - coverage/coverage-summary.json
  datastores:
    - artifact://ikevin127/expensify-app-mock
  acceptable: 5%

report:
  paths:
    - coverage/lcov.info
    - coverage/coverage-summary.json
  datastores:
    - artifact://ikevin127/expensify-app-mock

push:
  datastores:
    - artifact://ikevin127/expensify-app-mock
